#Dev profile for application properties

# SQL logging
# Modify properties to show SQL (Ex c3.1d)
spring.jpa.show-sql=true
# recreate table on startup
spring.jpa.hibernate.ddl-auto=create 

# Enable H2 console (Ex c3.1e)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

# H2 seurity bypass
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# Debug
logging.level.org.springframework.web=DEBUG