spring.application.name=littlefreelibrary

# REST API path
spring.data.rest.basePath=/api

# Application properties profile to be used
spring.profiles.active=dev
# dev or prod for production 
# or set an environment variable SPRING_PROFILES_ACTIVE=prod
